// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchMobile(ctx context.Context, in *SearchMobileRequest, opts ...grpc.CallOption) (SearchService_SearchMobileClient, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchMobile(ctx context.Context, in *SearchMobileRequest, opts ...grpc.CallOption) (SearchService_SearchMobileClient, error) {
	stream, err := c.cc.NewStream(ctx, &SearchService_ServiceDesc.Streams[0], "/pb.SearchService/SearchMobile", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchServiceSearchMobileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SearchService_SearchMobileClient interface {
	Recv() (*SearchMobileResponse, error)
	grpc.ClientStream
}

type searchServiceSearchMobileClient struct {
	grpc.ClientStream
}

func (x *searchServiceSearchMobileClient) Recv() (*SearchMobileResponse, error) {
	m := new(SearchMobileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	SearchMobile(*SearchMobileRequest, SearchService_SearchMobileServer) error
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchMobile(*SearchMobileRequest, SearchService_SearchMobileServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchMobile not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchMobile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchMobileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchServiceServer).SearchMobile(m, &searchServiceSearchMobileServer{stream})
}

type SearchService_SearchMobileServer interface {
	Send(*SearchMobileResponse) error
	grpc.ServerStream
}

type searchServiceSearchMobileServer struct {
	grpc.ServerStream
}

func (x *searchServiceSearchMobileServer) Send(m *SearchMobileResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchMobile",
			Handler:       _SearchService_SearchMobile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "search_service.proto",
}
